# We need a file with all the gene counts generated for each dataset. /
# We will join them using bash

## This file contains
# *The gene IDs (first column)
#  The dataset numbers (first row) and their gene counts generated by featurecounts

awk '{print $1, $NF}' 767_Counts.txt > f1
awk '{print $1, $NF}' counts760.txt > f2
awk '{print $1, $NF}' 782_Counts.txt > f3
awk '{print $1, $NF}' counts779.txt > f4
paste <(cut -d' ' -f1 f1) <(cut -d' ' -f2 f1) <(cut -d' ' -f2 f2) <(cut -d' ' -f2 f3) <(cut -d' ' -f2 f4) >> ASDvsTD_CountsF.txt

head ASDvsTD_CountsF.txt 
